"use client";
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";import{CUP_TEAMS,TEAM_NAMES,newSeason,readSeason,resetSeason,recordSeasonResult,readProfile}from"../game/cup";import ThemeToggle from"../game/ThemeToggle";import"../game/profile.css";import"./season.css";
export default function Season(){const r=useRouter(),[s,setS]=useState(null),[team,setTeam]=useState("england"),[p,setP]=useState(null);const load=()=>{let x=readSeason(),pr=readProfile();if(x){
// Backfill season results from the profile (season matches are only written to
// the profile at full-time; the season state catches up here). Match by COUNT,
// not timestamp: the profile entry and the season entry are written by two
// separate Date.now() calls, so an exact-timestamp check never matched and the
// same match was re-recorded on EVERY page visit (skipping rounds for free).
const played=(pr.results||[]).filter(z=>z.mode==="season"&&z.at>(x.startedAt||0));
const deficit=Math.max(0,played.length-(x.results||[]).length);
if(deficit>0){const missing=[...played].reverse().slice(-deficit);for(const z of missing){if(!x||x.eliminated||x.champion)break;x=recordSeasonResult(z.score)}}}
setS(x);setP(readProfile())};useEffect(load,[]);const start=()=>setS(newSeason(team));const opp=s?.round===1?s.bracket.quarter[1]:s?.round===2?s.bracket.semi[1]:s?.round===3?s.bracket.final[1]:null;const play=()=>{if(opp)r.push("/match?red="+s.team+"&blue="+opp+"&ai=1&side=home&time=6&play=1&mode=season")};const q=s?.bracket.quarter||[],sm=s?.bracket.semi||[],fn=s?.bracket.final||[];const slot=(id,i)=>id?<div className={id===s?.team?"team you":"team"}><span>{id===s?.team?"🐾 ":""}{TEAM_NAMES[id]||id}</span>{i===0&&s?.round===1?<small>YOU</small>:null}</div>:<div className="team muted">TBD</div>;return <main className="season-page"><header className="season-head"><button onClick={()=>r.push("/")}>← Main Menu</button><div><span>ANIMAL CUP REMASTERED</span><h1>🌟 Season Mode</h1></div><div className="season-tools"><span>🪙 {p?.coins||0}</span><ThemeToggle/></div></header>{!s?<section className="season-card"><span className="season-ribbon">FULL 8-TEAM SEASON</span><h2>Build a dynasty</h2><p>Choose a nation, develop your animals and fight through a real quarterfinal → semifinal → final bracket.</p><div className="team-picker">{CUP_TEAMS.map(id=><button className={team===id?"selected":""} key={id} onClick={()=>setTeam(id)}>{TEAM_NAMES[id]}</button>)}</div><button className="season-primary" onClick={start}>Start New Season</button></section>:<><section className="season-card"><div className="season-status"><span>SEASON • ROUND {s.round}/3</span><b>{s.champion?"🏆 CHAMPIONS":s.eliminated?"❌ ELIMINATED":"🔥 "+s.seasonWins+" wins"}</b></div><div className="bracket"><div><h3>Quarterfinals</h3>{[0,2,4,6].map(i=><div className="fixture" key={i}>{slot(q[i],i)}<b>VS</b>{slot(q[i+1],i+1)}</div>)}</div><div><h3>Semifinals</h3>{[0,2].map(i=><div className="fixture" key={i}>{slot(sm[i],i)}<b>VS</b>{slot(sm[i+1],i+1)}</div>)}</div><div><h3>Final</h3><div className="fixture">{slot(fn[0],0)}<b>VS</b>{slot(fn[1],1)}</div></div></div>{s.champion?<div className="season-hero">🏆<b>SEASON CHAMPION</b><span>Your dynasty is complete. Trophy and rewards saved.</span></div>:s.eliminated?<div className="season-hero">💪<b>Season over</b><span>Start another season to try a new bracket.</span></div>:<button className="season-primary" onClick={play}>Play Round {s.round} — {TEAM_NAMES[s.team]} vs {TEAM_NAMES[opp]}</button>}<button className="season-secondary" onClick={()=>{resetSeason();setS(null)}}>Start New Season</button></section><section className="season-card"><h2>📈 Season Progress</h2><div className="season-progress"><i style={{width:((s.seasonWins/3)*100)+"%"}}/></div><p>{s.results.length} of 3 matches completed • {s.results.filter(x=>x.score[0]>x.score[1]).length} wins</p></section></>}</main>}