"use client";
import { useEffect,useRef,useState } from "react";
import { useLocale } from "../i18n/LocaleProvider";
const KEY="animalCupMatchOptions", SK={up:"knockOn",right:"laneChange",down:"heelToHeel",left:"fakeShot"};
function inp(){if(!window.__touchInput)window.__touchInput={active:false,vx:0,vy:0,shoot:false,pass:false,sprint:false,throughPass:false,lob:false,tackle:false,finesse:false,chip:false,powerShot:false,switchPlayer:false,secondDefender:false,jockey:false};return window.__touchInput}
const timers=new Map();
function setA(n,v){const s=inp();s[n]=v;s.active=true} function rel(n){const s=inp();s[n]=false;s.active=s.vx!==0||s.vy!==0}
function pulse(n,ms=140){const s=inp();s.active=true;s[n]=true;clearTimeout(timers.get(n));timers.set(n,setTimeout(()=>{s[n]=false;s.active=s.vx!==0||s.vy!==0},ms))}
function buzz(ms=8){try{navigator.vibrate?.(ms)}catch{}} function powerBuzz(){try{navigator.vibrate?.([20,18,45])}catch{}} function cap(e){try{e.currentTarget.setPointerCapture?.(e.pointerId)}catch{}}
function ballMine(){try{const u=window.require?.("users")?.list?.[0],b=window.__matchGame?.pitch?.ball;return !!(u?.player?.hasBall||(b?.owner?.team&&u?.team===b.owner.team))}catch{return false}}
function opts(){try{const o=window.__acMatchOptions||JSON.parse(localStorage.getItem(KEY)||"{}");return{...o,scheme:o.scheme||"classic",switchMode:o.switchMode||"auto",switchDelay:Number(o.switchDelay||0),powerShotZoom:o.powerShotZoom!==false,skillMoves:{...SK,...(o.skillMoves||{})}}}catch{return{scheme:"classic",switchMode:"auto",switchDelay:0,powerShotZoom:true,skillMoves:SK}}}
function phaseOf(p){if(!p)return null;const r=String(p.restartType||p.restart||p.phase||"").toLowerCase();if(p.penalty||r.includes("penalty"))return"penalty";if(p.corner||r.includes("corner"))return"corner";if(p.freeKick||r.includes("free"))return"free";return null}
function nearest(){try{const u=window.require?.("users")?.list?.[0],t=u?.team,b=window.__matchGame?.pitch?.ball,a=[...(t?.players||[]),...(t?.members||[]),...(t?.children||[])];let best=null,bd=Infinity;for(const p of a){if(!p||p===u.player||!b)continue;const d=(p.x-b.x)**2+(p.y-b.y)**2;if(d<bd){bd=d;best=p}}return best}catch{return null}}
export default function TouchControls(){
 const {t}=useLocale(),base=useRef(null),thumb=useRef(null),stick=useRef(null),sp=useRef(null),sw=useRef(null),oneTimer=useRef(null),oneHeld=useRef(false),zoom=useRef(false);
 const [attack,setAttack]=useState(false),[o,setO]=useState({scheme:"classic",switchMode:"auto",switchDelay:0,powerShotZoom:true,skillMoves:SK}),[phase,setPhase]=useState(null);
 useEffect(()=>{inp();setO(opts());const f=e=>setO(x=>({...x,...e.detail,skillMoves:{...x.skillMoves,...(e.detail?.skillMoves||{})}}));window.addEventListener("ac-match-options",f);const p=e=>e.preventDefault();document.addEventListener("contextmenu",p,{passive:false});return()=>{window.removeEventListener("ac-match-options",f);document.removeEventListener("contextmenu",p)}},[]);
 useEffect(()=>{const iv=setInterval(()=>{try{const u=window.require?.("users")?.list?.[0],b=window.__matchGame?.pitch?.ball;setAttack(!!(u?.player?.hasBall||(b?.owner?.team&&b.owner.team===u?.team)))}catch{}setPhase(phaseOf(window.__matchGame?.pitch));},120);return()=>clearInterval(iv)},[]);
 useEffect(()=>{const iv=setInterval(()=>{if(o.switchMode!=="loose")return;try{const b=window.__matchGame?.pitch?.ball,u=window.require?.("users")?.list?.[0];if(!b||b.owner||!u?.player)return;const n=nearest();if(!n||sw.current)return;sw.current=setTimeout(()=>{sw.current=null;if(!window.__touchInput?.switchPlayer)pulse("switchPlayer",80)},Math.min(600,Math.max(0,o.switchDelay*60)))}catch{}},120);return()=>{clearInterval(iv);if(sw.current)clearTimeout(sw.current)}},[o.switchMode,o.switchDelay]);
 function down(e){cap(e);stick.current=e.pointerId;move(e)} function move(e){if(stick.current!==null&&e.pointerId!==stick.current)return;const r=base.current?.getBoundingClientRect();if(!r||!thumb.current)return;const m=Math.max(1,Math.min(r.width,r.height)*.36);let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>m){x=x/l*m;y=y/l*m}thumb.current.style.transform=`translate(${x}px,${y}px)`;const s=window.__acMatchOptions?.sensitivity||1;setA("vx",Math.max(-1,Math.min(1,x/m*s)));setA("vy",Math.max(-1,Math.min(1,y/m*s)))} function up(e){if(stick.current!==null&&e.pointerId!==stick.current)return;stick.current=null;if(thumb.current)thumb.current.style.transform="translate(0,0)";setA("vx",0);setA("vy",0)}
 function sprintDown(e){e.preventDefault();cap(e);sp.current=e.currentTarget;e.currentTarget.classList.add("is-down");setA("sprint",true);buzz(10)}
 function sprintUp(e){e.preventDefault();e.currentTarget.classList.remove("is-down");rel("sprint");sp.current=null}
 function hold(n,charge=false){return{onPointerDown:e=>{e.preventDefault();cap(e);e.currentTarget.classList.add("is-down");setA(n,true);buzz(10);if(charge)e.currentTarget.classList.add("is-charging")},onPointerUp:e=>{e.preventDefault();e.currentTarget.classList.remove("is-down","is-charging");rel(n);if(charge&&zoom.current){window.__matchZoom?.step?.(1/1.12);zoom.current=false}},onPointerCancel:e=>{e.currentTarget.classList.remove("is-down","is-charging");rel(n);if(charge&&zoom.current){window.__matchZoom?.step?.(1/1.12);zoom.current=false}},onPointerLeave:e=>{e.currentTarget.classList.remove("is-down","is-charging");rel(n);if(charge&&zoom.current){window.__matchZoom?.step?.(1/1.12);zoom.current=false}}}}
 useEffect(()=>()=>{if(zoom.current){window.__matchZoom?.step?.(1/1.12);zoom.current=false}window.__acShootStarted=0},[]);
 useEffect(()=>{const iv=setInterval(()=>{if(window.__touchInput?.shoot&&o.powerShotZoom&&ballMine()&&!zoom.current){const t0=window.__acShootStarted;if(t0&&performance.now()-t0>=300){window.__matchZoom?.step?.(1.12);zoom.current=true;powerBuzz()}}},40);return()=>clearInterval(iv)},[o.powerShotZoom]);
 function shootDown(e){hold("shoot",true).onPointerDown(e);window.__acShootStarted=performance.now()} function shootUp(e){hold("shoot",true).onPointerUp(e);window.__acShootStarted=0} function shootCancel(e){hold("shoot",true).onPointerCancel(e);window.__acShootStarted=0}
 function tap(n){return{onPointerDown:e=>{e.preventDefault();cap(e);e.currentTarget.classList.add("is-down");pulse(n);buzz(8);if(phase)setPhase(null)},onPointerUp:e=>e.currentTarget.classList.remove("is-down"),onPointerCancel:e=>e.currentTarget.classList.remove("is-down")}}
 function oneButton(attackMode){return{onPointerDown:e=>{e.preventDefault();cap(e);e.currentTarget.classList.add("is-down");oneHeld.current=false;clearTimeout(oneTimer.current);oneTimer.current=setTimeout(()=>{oneHeld.current=true;if(attackMode){pulse("pass")}else{setA("sprint",true)}},180)},onPointerUp:e=>{e.preventDefault();e.currentTarget.classList.remove("is-down");clearTimeout(oneTimer.current);if(oneHeld.current){if(!attackMode)rel("sprint")}else pulse(attackMode?"shoot":"tackle");oneHeld.current=false},onPointerCancel:e=>{e.currentTarget.classList.remove("is-down");clearTimeout(oneTimer.current);rel(attackMode?"shoot":"sprint");oneHeld.current=false}}}
 const two=o.scheme==="twoButton",one=o.scheme==="oneButton";
 const sprintStyle={position:"fixed",right:"calc(20px + env(safe-area-inset-right, 0px))",bottom:"calc(20px + env(safe-area-inset-bottom, 0px))",width:"78px",height:"78px",fontSize:"12.5px"};
 return <div className="tc" aria-label={t("match.mobileControls")}>
  <div className="tc-stick" ref={base} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><span className="tc-thumb" ref={thumb}/><span className="tc-stick-label">MOVE</span></div>
  {one||two?<div className={`fc-scheme fc-scheme--${o.scheme}`}>{two?<><button type="button" className="fc-scheme-btn fc-scheme-btn--primary" {...(attack?hold("shoot",true):tap("tackle"))}>{attack?t("match.scheme.action1Attack"):t("match.scheme.action1Defend")}</button><button type="button" className="fc-scheme-btn" {...(attack?hold("pass"):hold("sprint"))}>{attack?t("match.scheme.action2Attack"):t("match.scheme.action2Defend")}</button></>:<button type="button" className="fc-scheme-btn fc-scheme-btn--primary" {...oneButton(attack)}>{attack?t("match.scheme.oneAttack"):t("match.scheme.oneDefend")}<small>{t("match.scheme.holdAlt")}</small></button>}</div>:
  <div className="fc-cluster">
   <button type="button" className="fc-btn fc-btn--big fc-slot-big fc-ring-sprint" style={sprintStyle} ref={sp} onPointerDown={sprintDown} onPointerUp={sprintUp} onPointerCancel={sprintUp} onPointerLeave={sprintUp}>{t("match.sprint")}</button>
   <div className={`fc-group ${attack?"":"is-off"}`} aria-hidden={!attack}><button type="button" className="fc-btn fc-btn--main fc-slot-top fc-ring-shoot" onPointerDown={shootDown} onPointerUp={shootUp} onPointerCancel={shootCancel} onPointerLeave={shootCancel}>{t("match.shoot")}<svg className="fc-power" viewBox="0 0 100 100" aria-hidden><circle cx="50" cy="50" r="46" pathLength="100"/></svg></button><button type="button" className="fc-btn fc-btn--main fc-slot-mid fc-ring-through" {...tap("throughPass")}>{t("match.through")}</button><button type="button" className="fc-btn fc-btn--main fc-slot-left fc-ring-pass" {...tap("pass")}>{t("match.pass")}</button><button type="button" className="fc-btn fc-btn--sat fc-arc-a fc-ring-finesse" {...hold("finesse")}>{t("match.finesse")}</button><button type="button" className="fc-btn fc-btn--lob fc-arc-b fc-ring-lob" {...tap("lob")}>{t("match.lob")}</button><button type="button" className="fc-btn fc-btn--sat fc-arc-c fc-ring-chip" {...tap("chip")}>{t("match.chip")}</button><button type="button" className="fc-btn fc-btn--sat fc-arc-d fc-ring-power" {...hold("powerShot")}>{t("match.power")}</button></div>
   <div className={`fc-group ${attack?"is-off":""}`} aria-hidden={attack}><button type="button" className="fc-btn fc-btn--main fc-slot-top fc-ring-tackle" {...tap("tackle")}>{t("match.tackle")}</button><button type="button" className="fc-btn fc-btn--main fc-slot-mid fc-ring-clear" {...tap("lob")}>{t("match.clear")}</button><button type="button" className="fc-btn fc-btn--main fc-slot-left fc-ring-switch" {...tap("switchPlayer")}>{t("match.switch")}</button><button type="button" className="fc-btn fc-btn--sat fc-arc-b fc-ring-second" {...hold("secondDefender")}>{t("match.secondDefender")}</button><button type="button" className="fc-btn fc-btn--sat fc-arc-c fc-ring-jockey" {...hold("jockey")}>{t("match.jockey")}</button></div>
  </div>}
  {phase?<div className={`fc-setpiece fc-setpiece--${phase}`}><button type="button" {...tap(phase==="penalty"?"shoot":"lob")}>{phase==="penalty"?t("match.setPiece.placement"):t("match.setPiece.cross")}</button><button type="button" {...tap(phase==="penalty"?"chip":"pass")}>{phase==="penalty"?t("match.setPiece.chip"):t("match.setPiece.short")}</button><button type="button" {...tap(phase==="penalty"?"powerShot":"throughPass")}>{phase==="penalty"?t("match.setPiece.power"):t("match.setPiece.low")}</button></div>:null}
 </div>;
}
