const PROFILE="animalCupRemastered.profile.v1",CUP="animalCupRemastered.cup.v2",SEASON="animalCupRemastered.season.v1",THEME="animalCupRemastered.theme";
export const CUP_TEAMS=["england","france","germany","spain","portugal","brazil","argentina","usa"];
export const TEAM_NAMES={england:"England",france:"France",germany:"Germany",spain:"Spain",portugal:"Portugal",brazil:"Brazil",argentina:"Argentina",usa:"USA"};
const empty=()=>({matches:0,wins:0,draws:0,losses:0,goals:0,conceded:0,trophies:0,coins:0,streak:0,bestStreak:0,achievements:[],results:[],unlocks:["classic","classic-ball"],upgrades:{speed:1,shoot:1,pass:1},daily:{date:"",claimed:false}});
const arr=(x,d)=>Array.isArray(x)?x:d;
export function readProfile(){if(typeof window==="undefined")return empty();try{const p=JSON.parse(localStorage.getItem(PROFILE)||"null")||{},d=empty();return{...d,...p,achievements:arr(p.achievements,[]),results:arr(p.results,[]),unlocks:arr(p.unlocks,d.unlocks),upgrades:{...d.upgrades,...(p.upgrades||{})},daily:{...d.daily,...(p.daily||{})}}}catch{return empty()}}
export function saveProfile(p){if(typeof window!=="undefined"){localStorage.setItem(PROFILE,JSON.stringify(p));window.dispatchEvent(new Event("ac-profile"))}return p}
export function readTheme(){if(typeof window==="undefined")return"light";return localStorage.getItem(THEME)||"light"}
export function setTheme(theme){if(typeof window!=="undefined"){localStorage.setItem(THEME,theme);document.documentElement.dataset.theme=theme;document.body.classList.toggle("ac-dark",theme==="dark")}}
const award=(p,id)=>{if(!p.achievements.includes(id))p.achievements.push(id)};
const unlock=(p,id)=>{if(!p.unlocks.includes(id))p.unlocks.push(id)};
export function recordMatch({score,red="red",blue="blue",mode="quick"}){const[r,b]=score.map(Number),p=readProfile();p.matches++;p.goals+=r;p.conceded+=b;p.results.unshift({red,blue,score:[r,b],mode,at:Date.now()});p.results=p.results.slice(0,100);if(r>b){p.wins++;p.streak++;p.bestStreak=Math.max(p.bestStreak,p.streak);p.coins+=25}else if(r===b){p.draws++;p.streak=0;p.coins+=10}else{p.losses++;p.streak=0;p.coins+=5}if(p.matches>=1)award(p,"first-match");if(p.wins>=1)award(p,"first-win");if(p.wins>=5)award(p,"five-wins");if(p.bestStreak>=3)award(p,"hot-streak");if(p.goals>=10)award(p,"ten-goals");if(p.goals>=25)award(p,"goal-machine");if(p.wins>=10)unlock(p,"pro-ball");if(p.trophies>=1)unlock(p,"champion-stadium");return saveProfile(p)}
export function getAchievementList(){return[["first-match","First Match"],["first-win","First Win"],["five-wins","Five Wins"],["hot-streak","Hot Streak"],["ten-goals","Ten Goals"],["goal-machine","Goal Machine"],["champion","Champion"],["daily-hero","Daily Hero"]]}
export function getUnlocks(p=readProfile()){return[{id:"classic",name:"Classic Stadium",cost:0,kind:"stadium",icon:"🏟️"},{id:"sunset",name:"Sunset Stadium",cost:150,kind:"stadium",icon:"🌅"},{id:"champion-stadium",name:"Champion Stadium",cost:300,kind:"stadium",icon:"🏆"},{id:"classic-ball",name:"Classic Ball",cost:0,kind:"ball",icon:"⚽"},{id:"pro-ball",name:"Pro Ball",cost:200,kind:"ball",icon:"🟠"}].map(x=>({...x,unlocked:p.unlocks.includes(x.id)}))}
export function buyUnlock(id){const p=readProfile(),item=getUnlocks(p).find(x=>x.id===id);if(!item||item.unlocked||p.coins<item.cost)return false;p.coins-=item.cost;unlock(p,id);saveProfile(p);return true}
export function upgradeStat(stat){const p=readProfile(),level=Number(p.upgrades[stat]||1),cost=level*100;if(level>=5||p.coins<cost)return false;p.coins-=cost;p.upgrades[stat]=level+1;saveProfile(p);return true}
export function readCup(){if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem(CUP)||"null")}catch{return null}}
export function writeCup(c){localStorage.setItem(CUP,JSON.stringify(c));return c}
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
export function newCup(team){const others=shuffle(CUP_TEAMS.filter(t=>t!==team));const teams=[team,...others];return writeCup({version:2,team,round:1,wins:0,eliminated:false,champion:false,startedAt:Date.now(),results:[],bracket:{quarter:[...teams],semi:[],final:[],champion:null}})}
export function resetCup(){if(typeof window!=="undefined")localStorage.removeItem(CUP)}
export function recordCupResult(score){const c=readCup();if(!c||c.eliminated||c.champion)return c;const[r,b]=score.map(Number);const opp=c.round===1?c.bracket.quarter[1]:c.round===2?c.bracket.semi[1]:c.bracket.final[1];c.results.push({round:c.round,opponent:opp,score:[r,b],at:Date.now()});if(r<=b){c.eliminated=true;return writeCup(c)}c.wins++;if(c.round===1){c.bracket.semi=[c.team,c.bracket.quarter[2]];c.round=2}else if(c.round===2){c.bracket.final=[c.team,c.bracket.semi[1]];c.round=3}else{c.champion=true;c.bracket.champion=c.team;const p=readProfile();p.trophies++;p.coins+=250;award(p,"champion");unlock(p,"champion-stadium");saveProfile(p)}return writeCup(c)}
export function readSeason(){if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem(SEASON)||"null")}catch{return null}}
export function saveSeason(s){if(typeof window!=="undefined")localStorage.setItem(SEASON,JSON.stringify(s));return s}
export function resetSeason(){if(typeof window!=="undefined")localStorage.removeItem(SEASON)}
export function newSeason(team){const others=shuffle(CUP_TEAMS.filter(t=>t!==team));const teams=[team,...others];return saveSeason({version:1,team,round:1,eliminated:false,champion:false,teams,bracket:{quarter:[...teams],semi:[],final:[]},results:[],startedAt:Date.now(),seasonWins:0})}
export function recordSeasonResult(score){const s=readSeason();if(!s||s.eliminated||s.champion)return s;const[r,b]=score.map(Number);const q=s.bracket.quarter;const opp=s.round===1?q[1]:s.round===2?s.bracket.semi[1]:s.bracket.final[1];s.results.push({round:s.round,opponent:opp,score:[r,b],at:Date.now()});if(r<=b){s.eliminated=true;return saveSeason(s)}s.seasonWins++;if(s.round===1){s.bracket.semi=[s.team,q[2],q[4],q[6]];s.round=2}else if(s.round===2){s.bracket.final=[s.team,s.bracket.semi[2]];s.round=3}else{s.champion=true;const p=readProfile();p.trophies++;p.coins+=500;award(p,"champion");unlock(p,"champion-stadium");saveProfile(p)}return saveSeason(s)}
export function dailyChallenge(){const date=new Date().toISOString().slice(0,10),p=readProfile();if(p.daily.date!==date){p.daily={date,claimed:false};saveProfile(p)}const n=Number(date.replaceAll("-","")),i=n%CUP_TEAMS.length;return{date,title:"Daily Derby",description:"Win today's one-match challenge.",team:CUP_TEAMS[i],opponent:CUP_TEAMS[(i+3)%CUP_TEAMS.length],reward:100,claimed:p.daily.claimed}}
export function claimDaily(){const c=dailyChallenge();if(c.claimed)return false;const p=readProfile();p.daily={date:c.date,claimed:true};p.coins+=c.reward;award(p,"daily-hero");saveProfile(p);return true}
