const KEY="animalCupRemastered.gameplay.v1";
export const PRESETS={arcade:{preset:"arcade",playerSpeedMultiplier:1.14,accelerationMultiplier:1.16,passSpeedMultiplier:1.12,passAccuracyBase:.92,shotAccuracyBase:.9,shotSpeedMultiplier:1.08,dribbleControl:1.12,skillMoveMultiplier:1.08,aiDefendAggression:.38,aiAssist:.2,foulFrequency:.28,physicality:.9,keeperReaction:.92,offsideTolerance:.22,staminaDrain:.9},authentic:{preset:"authentic",playerSpeedMultiplier:1,accelerationMultiplier:.94,passSpeedMultiplier:.96,passAccuracyBase:.78,shotAccuracyBase:.78,shotSpeedMultiplier:.98,dribbleControl:.94,skillMoveMultiplier:.96,aiDefendAggression:.5,aiAssist:.55,foulFrequency:.45,physicality:1.08,keeperReaction:1.04,offsideTolerance:.08,staminaDrain:1.08}};
const defaults={preset:"arcade",assistedPassing:true,assistedShooting:true,aiAssist:"medium",aimGuide:false};
export function readGameplay(){if(typeof window==="undefined")return defaults;try{return{...defaults,...(JSON.parse(localStorage.getItem(KEY)||"null")||{})}}catch{return defaults}}
export function saveGameplay(v){if(typeof window!=="undefined")localStorage.setItem(KEY,JSON.stringify(v));return v}
export function getGameplayConfig(){const s=readGameplay();return PRESETS[s.preset]||PRESETS.arcade}
export function passOutcome({passing=70,pressure=0.2,distance=1,through=false,lofted=false}={}){const c=getGameplayConfig(),risk=pressure*.45+Math.min(1,distance/30)*.2+(lofted?.16:0);return{accuracy:Math.max(.2,Math.min(.99,c.passAccuracyBase+(passing-70)/500-risk+(through?.02:0))),speed:c.passSpeedMultiplier*(through?1.06:lofted?.92:1),curve:through?Math.max(0,(passing-55)/100):0}}
export function shotOutcome({shooting=70,pressure=0.2,distance=1,finesse=false,chip=false,power=false}={}){const c=getGameplayConfig(),penalty=pressure*.42+Math.min(1,distance/35)*.16+(power?.12:0);let accuracy=c.shotAccuracyBase+(shooting-70)/450-penalty;if(finesse)accuracy-=.025;if(chip)accuracy-=.04;return{accuracy:Math.max(.16,Math.min(.98,accuracy)),speed:c.shotSpeedMultiplier*(power?1.22:finesse?.94:chip?.78:1),curve:finesse?Math.max(.12,shooting/100):0}}
export function tackleOutcome({defending=70,physical=70,attackerPhysical=70,position=0.5,timing=0.5,fromBehind=false}={}){const c=getGameplayConfig(),base=.42+(defending-70)/260+(physical-attackerPhysical)/500+(position-.5)*.28+(timing-.5)*.3,foul=(fromBehind?.18:0)+(timing<.25?.12:0)+c.foulFrequency*.1;return{success:Math.max(.08,Math.min(.92,base)),foul:Math.max(.02,Math.min(.55,foul)),card:foul>.42?"red":foul>.24?"yellow":null}}
export function physicalOutcome(a={},b={}){const c=getGameplayConfig(),ap=(a.physical||70)*c.physicality+(a.pace||70)*.12,bp=(b.physical||70)*c.physicality+(b.pace||70)*.12;return{winner:ap>=bp?"a":"b",margin:Math.abs(ap-bp)}}
export const RULE_STATES=["kickoff","inPlay","cornerStage1","cornerStage2","freeKickAim","penaltyAim","goalKick","throwIn","halfTime","fullTime"];
export const SHOT_TYPES=["normal","finesse","chip","power"];
export const PASS_TYPES=["ground","through","lofted","cross"];
